name: Deploy MkDocs Site
on:
  push:
    branches:
      - main
      - master
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - name: Install Dependencies
        run: |
          pip install mkdocs-material
          pip install "mkdocstrings[python]"
          pip install pillow cairosvg
      - name: Prevent Jekyll Build
        run: touch docs/.nojekyll
      - name: Deploy MkDocs Site
        run: mkdocs gh-deploy --force